site_name: Geoservicios para Smart Cities
site_url: https://gss-mtig.github.io/gss-mtig/
site_description: Geoservicios para Smart Cities.
site_author: gss-mtig
theme:
  name: 'material'
  language: 'es'
  highlightjs: true

markdown_extensions:
  - codehilite:
      linenums: True
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
repo_url: "https://github.com/gss-mtig/gss-mtig"

nav:
- Home: index.md
- 1. Introducción a las Smart Cities: 1_introduccion_a_las_smart_cities.md
- 2. Introducción al Open data: 2_introduccion_open_data.md
- Servicios Open data:
  - 2.1. API servicios Open data (CKAN y SOCRATA): 2_1_apis_y_servicios_open_data.md
- 3. Conceptos Vector Tiles: 3_conceptos_vector_tiles.md
- 4. Visualización con Kepler.gl: 4_visualizacion_kepler.md
- 5. Herramientas de visualización de datos: 5_herramientas_visualizacion_datos.md
- 6. Conceptos básicos de Geoservicios: 6_conceptos_geoservicios.md
- 7. Ejemplo servicio WMS: 7_ejemplo_servicio_wms.md
- 8. Consideraciones sobre servicios Open data: 8_consideraciones_servicios_opendata.md
- 9. Ejemplo servicio aparcamientos PMR Zaragoza: 8_ejemplo_parking_movilidad_reducida_zaragoza.md
- 9. Ejemplo servicio bicing Barcelona: 9_ejemplo_servicio_bicing_bcn.md
- 10. Ejemplo servicio bicing Barcelona (VectorTiles): 10_ejemplo_servicio_bicing_bcn_vt.md
- 11. Consideraciones sobre servicios de Sensores: 11_consideraciones_servicios_realtime_sensores.md
- 12. Ejemplo Sentilo ACA: 12_ejemplo_sentilo_aca.md
- 13. Geoservicios realtime: 13_geoservicios_realtime.md
- 14. Herramientas de visualización geoservicios: 14_herramientas_visualizacion_geoservicios.md
- 16. Ejemplo Geocodificador: 15_ejemplo_geocodificador.md
- 17. Ejemplo Mobility: 16_ejemplo_mobility.md
- 18. Ejemplo servicio realtime para compartir la ubicación: 17_ejemplo_geoservicio_realtime.md
- 19. Ejemplo Trenes realtime: 19_ejemplo_fgc_realtime.md
- 20. Ejemplo GTFS: 18_ejemplo_gtfs.md

plugins:
    - search
